/**
 * Export results to CSV format
 */
export function downloadCSV({ jdTitle, candidateName, score, matchedSkills, suggestions }) {
  const timestamp = new Date().toISOString()
  const rows = [
    ['FitForge Analysis Report'],
    ['Generated', timestamp],
    ['Job Title', jdTitle || '-'],
    ['Candidate Name', candidateName || '-'],
    [''],
    ['Overall Score', score],
    [''],
    ['Matched Skills', matchedSkills.length > 0 ? matchedSkills.join(', ') : 'None'],
    [''],
    ['Top Suggestions', suggestions.length > 0 ? suggestions.join(', ') : 'None'],
  ]
  
  const csvContent = rows.map(row => row.map(cell => `"${cell}"`).join(',')).join('\n')
  downloadFile(csvContent, `fitforge-analysis-${Date.now()}.csv`, 'text/csv')
}

/**
 * Export leaderboard to CSV
 */
export function downloadLeaderboardCSV(leaderboard) {
  const timestamp = new Date().toISOString()
  const rows = [
    ['FitForge Leaderboard Report'],
    ['Generated', timestamp],
    [''],
    ['Rank', 'Candidate Name', 'Score', 'Top Missing Skills'],
  ]
  
  leaderboard.forEach((row, idx) => {
    rows.push([
      idx + 1,
      row.candidateName,
      row.score,
      (row.topMissing || []).join('; ') || '-'
    ])
  })
  
  const csvContent = rows.map(row => row.map(cell => `"${cell}"`).join(',')).join('\n')
  downloadFile(csvContent, `fitforge-leaderboard-${Date.now()}.csv`, 'text/csv')
}

/**
 * Export results to PDF format (text-based)
 */
export function downloadPDF({ jdTitle, candidateName, score, label, matchedSkills, missingSkills, suggestions }) {
  const timestamp = new Date().toISOString()
  
  const content = `
╔═══════════════════════════════════════════════════════════════════╗
║                    FITFORGE ANALYSIS REPORT                       ║
╚═══════════════════════════════════════════════════════════════════╝

Generated: ${timestamp}
Job Title: ${jdTitle || 'N/A'}
Candidate: ${candidateName || 'N/A'}

═══════════════════════════════════════════════════════════════════

OVERALL ASSESSMENT

Score: ${score}/100
Rating: ${label}

═══════════════════════════════════════════════════════════════════

MATCHED SKILLS (${matchedSkills.length})

${matchedSkills.length > 0 ? matchedSkills.map((s, i) => `  ${i + 1}. ${s}`).join('\n') : '  None found'}

═══════════════════════════════════════════════════════════════════

MISSING SKILLS (${missingSkills.length})

${missingSkills.length > 0 ? missingSkills.map((s, i) => `  ${i + 1}. ${s}`).join('\n') : '  None'}

═══════════════════════════════════════════════════════════════════

TOP 5 RECOMMENDATIONS

${suggestions.length > 0 ? suggestions.map((s, i) => `  ${i + 1}. ${s}`).join('\n') : '  No suggestions at this time'}

═══════════════════════════════════════════════════════════════════

Generated by FitForge - HR Role-Fit Analyzer
Privacy-first, client-only analysis tool
  `.trim()
  
  downloadFile(content, `fitforge-report-${Date.now()}.txt`, 'text/plain')
}

/**
 * Helper to trigger file download
 */
function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
